name: Artifactory Docker CI

env:
  REPO_NAME: elilillyco-github-actions-docker-lc.jfrog.io

on:
  push:
    branches: [dev, develop, qa, $default-branch]
  pull_request:
    branches: [dev, develop, qa, $default-branch]

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Get Event Data
        run: |
          echo "Event type: ${{ github.event_name }}"
          if [[ ${{ github.event_name }} == "pull_request" ]] 
          then
            echo "Source Branch: ${{ github.head_ref }}"
            echo "Target Branch: ${{ github.base_ref }}"
          else
            echo "Triggered by branch/tag: ${{ github.ref }}"
          fi
          echo "Commit Sha: ${{ github.sha }}"
          echo "Event Actor: ${{ github.actor }}"

      - name: Abort Previous Builds
        uses: potiuk/cancel-workflow-runs@v4_8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          cancelMode: duplicates

  lint:
    name: Lint Dockerfile
    runs-on: ubuntu-latest
    needs: [setup]
    timeout-minutes: 15
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v3
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_DOCKERFILE: true
          VALIDATE_DOCKERFILE_HADOLINT: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  vulnerability_check:
    name: Snyk Vulnerability Check
    runs-on: ubuntu-latest
    needs: [setup]
    timeout-minutes: 5
    strategy:
      matrix:
        directory:
          - './folder1'
          - './folder2'
        include:
        - directory: './folder1'
          APP_NAME: 'apptestone'
          VERSION: latest
          
        - directory: './folder2'
          APP_NAME: 'apptesttwo'
          VERSION: version1.0
    defaults:
      run:
        working-directory: ${{ matrix.directory }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Build and tag the Docker image
        run: docker build -t ${{env.REPO_NAME}}/${{matrix.APP_NAME}}:${{matrix.VERSION}} .

      - name: Check Open Source Dependency Security
        # Snyk can be used to break the build when it detects vulnerabilities.
        continue-on-error: true
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
      with:
          image: ${{env.REPO_NAME}}/${{matrix.APP_NAME}}
          args: --file=Dockerfile
          # To see results and fail build on failure, command should be test
          command: test
          json: true

      - name: Upload Snyk Results
        uses: actions/upload-artifact@v2
        with:
          name: Snyk-results-summary
          path: snyk.json

